version: '3.8'
services:
  web:
    build:
      context: .
    command: gunicorn --bind 0.0.0.0:8000 intants_website.wsgi --workers=4
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    expose:
      - "8000"
    networks:
      - django-network
  nginx:
    build: nginx
    restart: always
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - django-network
networks:
  django-network:
    name: django-network
volumes:
  media_volume: null
  static_volume: null
